# Generated by Django 4.2.4 on 2023-08-23 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmodel',
            options={'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
    ]
