# Generated by Django 4.2.4 on 2023-08-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0003_eventmodel_teacher_alter_eventmodel_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
