# Generated by Django 4.2.4 on 2023-08-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0004_eventmodel_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='is_active',
            new_name='is_paid',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='status',
            field=models.CharField(choices=[('P', 'planned'), ('D', 'done'), ('C', 'canceled')], default='P', max_length=10),
        ),
    ]
