# Generated by Django 4.2.4 on 2023-08-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0005_rename_is_active_eventmodel_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmodel',
            options={'ordering': ['datetime'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='time',
            new_name='datetime',
        ),
    ]
