# Generated by Django 4.2.4 on 2023-08-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0006_alter_eventmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='status',
            field=models.CharField(choices=[('P', 'planned'), ('M', 'missed'), ('D', 'done'), ('C', 'canceled')], default='P', max_length=10),
        ),
    ]
