# Generated by Django 4.2.4 on 2023-08-31 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0007_alter_eventmodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmodel',
            options={'ordering': ['-datetime'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
    ]
