# Generated by Django 4.2.4 on 2023-09-15 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_calendar', '0008_alter_eventmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
