# Generated by Django 4.2.4 on 2023-09-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('translate', models.CharField(max_length=255)),
                ('lang', models.CharField(choices=[('eng', 'English'), ('fr', 'French'), ('sp', 'Spanish')], max_length=10)),
                ('sentences', models.TextField(max_length=255, null=True)),
            ],
        ),
    ]
