# Generated by Django 4.2.4 on 2023-09-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_words', '0002_exercise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': 'Слово для изучения', 'verbose_name_plural': 'Слова для изучения'},
        ),
        migrations.AlterField(
            model_name='word',
            name='sentences',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
