# Generated by Django 4.2.4 on 2023-09-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_words', '0003_alter_word_options_alter_word_sentences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='lang',
            field=models.CharField(choices=[('eng', 'English'), ('fr', 'French'), ('sp', 'Spanish')], default='eng', max_length=10),
        ),
    ]
