# Generated by Django 4.2.4 on 2023-09-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_words', '0005_alter_exercise_exercise_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='word',
        ),
        migrations.AddField(
            model_name='exercise',
            name='words',
            field=models.ManyToManyField(to='exercises_words.word'),
        ),
    ]
