# Generated by Django 4.2.4 on 2024-01-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_words', '0007_remove_exercise_exercise_number_exerciseresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
