# Generated by Django 4.2.4 on 2024-01-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_words', '0008_word_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='is_active',
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
