# Generated by Django 4.2.4 on 2024-01-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_words', '0009_remove_word_is_active_exercise_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='words',
            field=models.ManyToManyField(to='exercises_words.word', verbose_name='Слова'),
        ),
    ]
