# Generated by Django 4.2.4 on 2023-11-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_projecttype_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='from_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='to_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
