# Generated by Django 4.2.4 on 2023-11-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_project_from_date_project_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='from_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
